// Compound words that always keep their hyphen when split at a line end
// (matched case-insensitively against the full compound).
export const defaultKeepHyphens = [
  "Peer-to-Peer",
  "E-Mail",
  "Re-Entry",
  "state-of-the-art",
  "know-how",
  "Up-to-date",
  "long-term",
  "so-called",
  "full-time",
  "part-time",
  "short-term",
  "well-known",
  "make-up",
  "old-fashioned",
  "large-scale",
  "day-to-day",
  "co-ordination",
  "well-being",
  "in-house",
  "co-operate",
  "t-shirt",
  "follow-up",
  "right-hand",
  "x-ray",
];
